services:
  speaches:
    # Target: Jetson / aarch64
    platform: linux/arm64
    image: speaches:jetson-latest

    build:
      context: .
      dockerfile: Dockerfile.l4t
      args:
        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack:r36.4.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub

volumes:
  hf-hub-cache:
